name: C++ CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt-get install -y clang-format
      - name: Check formatting
        run: |
          find src -name "*.cpp" -exec clang-format --dry-run --Werror {} +

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy
      - name: Generate compile_commands.json
        run: |
          cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Run clang-tidy
        run: |
          clang-tidy src/*.cpp -p build

  memory-check-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build
      - name: Update package list
        run: sudo apt-get update
      - name: Install Valgrind
        run: sudo apt-get install -y valgrind --fix-missing
      - name: Run Valgrind
        run: valgrind --leak-check=full ./build/examples

memory-check-windows:
  runs-on: windows-latest
  steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build --config Debug
    - name: Install Dr. Memory
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/DynamoRIO/drmemory/releases/download/release_2.6.0/DrMemory-Windows-2.6.0.zip" -OutFile drmemory.zip
        Expand-Archive -Path drmemory.zip -DestinationPath .
    - name: Run Dr. Memory
      shell: cmd
      run: |
        set PATH=%PATH%;%CD%\DrMemory-Windows-2.6.0\bin
        drmemory -ignore_kernel -- build\Debug\examples.exe